apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.name }}
  annotations:
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/autoscaler-class: none
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    deploymentStrategy:
      {{- toYaml .Values.predictor.deploymentStrategy | nindent 6 }}
    model:
      modelFormat:
        name: {{ .Values.model.format }}
        version: "1"
      runtime: {{ .Values.runtime.name }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
