apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qwen-wsl2-gpu
  namespace: argocd
spec:
  sourceRepos:
    - {{ .Values.repoUrl | quote }}
    - quay.io/jetstack/charts
    - ghcr.io/kserve/charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: kserve
    - server: https://kubernetes.default.svc
      namespace: qwen-serving
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
